openapi: 3.0.3
info:
  title: Task Management API
  version: 1.0.0
  description: API pour gérer des tâches (Task)

servers:
  - url: http://localhost:3000

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Faire les courses
        completed:
          type: boolean
          example: false
      required:
        - id
        - title
        - completed

paths:
  /tasks:
    get:
      summary: Retourne la liste des tâches
      responses:
        '200':
          description: Liste des tâches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    post:
      summary: Crée une liste de nouvelles tâches
      requestBody:
        description: Liste des tâches à créer
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  title:
                    type: string
                    example: Faire les courses
                  completed:
                    type: boolean
                    example: false
                required:
                  - title
                  - completed
      responses:
        '201':
          description: Liste des tâches créées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    delete:
      summary: Supprime une liste de tâches par leurs IDs
      requestBody:
        description: Liste des IDs des tâches à supprimer
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                example: 1
      responses:
        '200':
          description: Liste des tâches supprimées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /tasks/{id}:
    get:
      summary: Retourne une tâche par son ID
      parameters:
        - name: id
          in: path
          description: ID de la tâche
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Tâche trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task not found

    delete:
      summary: Supprime une tâche par son ID
      parameters:
        - name: id
          in: path
          description: ID de la tâche à supprimer
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Tâche supprimée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task not found
